In [39]:
from tensorflow.keras.preprocessing.text  import one_hot

In [40]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [41]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [42]:
## Define the vocabulary size
voc_size=10000

In [43]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[945, 660, 3931, 1602],
 [945, 660, 3931, 2935],
 [945, 5675, 3931, 4258],
 [9773, 1657, 7404, 5510, 416],
 [9773, 1657, 7404, 5510, 1312],
 [2559, 945, 193, 3931, 7183],
 [8250, 1871, 1030, 5510]]

In [44]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [45]:
import numpy as np

In [34]:
sent_length = 8

In [46]:

embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length )
print(embedded_docs)

[[   0    0    0    0  945  660 3931 1602]
 [   0    0    0    0  945  660 3931 2935]
 [   0    0    0    0  945 5675 3931 4258]
 [   0    0    0 9773 1657 7404 5510  416]
 [   0    0    0 9773 1657 7404 5510 1312]
 [   0    0    0 2559  945  193 3931 7183]
 [   0    0    0    0 8250 1871 1030 5510]]


In [36]:
dim =10

In [37]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [48]:
model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[[ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.0306572 , -0.01606121,  0.03819044, -0.01181732,
          0.04253313, -0.02096562,  0.04463389,  0.01309038,
          0.04469969, -0.02090853],
        [ 0.01604425, -0.01664206, -0.03239702, -0.04394778,
          0.04513887,  0.02918274,  0.00831332,  0.00702173,
         -0.04464865,  0.04429239],
        [ 0.02379468, -0.02839651, -0.01274328, -0.0

In [51]:
embedded_docs[0]

array([   0,    0,    0,    0,  945,  660, 3931, 1602], dtype=int32)

In [54]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


array([[[ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.01754164,  0.04558914,  0.01481005, -0.01391177,
          0.01356692, -0.0209995 ,  0.00058817,  0.00395582,
          0.03319129, -0.0129903 ],
        [ 0.0306572 , -0.01606121,  0.03819044, -0.01181732,
          0.04253313, -0.02096562,  0.04463389,  0.01309038,
          0.04469969, -0.02090853],
        [ 0.01604425, -0.01664206, -0.03239702, -0.04394778,
          0.04513887,  0.02918274,  0.00831332,  0.00702173,
         -0.04464865,  0.04429239],
        [ 0.02379468, -0.02839651, -0.01274328, -0.0